// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Animation.CornerRadiusTransition"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Avalonia.Animation.CornerRadiusTransition"/> class.</returns>
    public static Avalonia.Animation.CornerRadiusTransition CornerRadiusTransition()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Animation.CornerRadiusTransition"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Avalonia.Animation.CornerRadiusTransition"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Animation.CornerRadiusTransition"/> class.</returns>
    public static Avalonia.Animation.CornerRadiusTransition CornerRadiusTransition(out Avalonia.Animation.CornerRadiusTransition @ref)
        => @ref = new();
}
