// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Helpers.ConditionalXAML.If"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="SukiUI.Helpers.ConditionalXAML.If"/> class.</returns>
    public static SukiUI.Helpers.ConditionalXAML.If If()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Helpers.ConditionalXAML.If"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="SukiUI.Helpers.ConditionalXAML.If"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="SukiUI.Helpers.ConditionalXAML.If"/> class.</returns>
    public static SukiUI.Helpers.ConditionalXAML.If If(out SukiUI.Helpers.ConditionalXAML.If @ref)
        => @ref = new();
}
