// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Layout.Layoutable"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Avalonia.Layout.Layoutable"/> class.</returns>
    public static Avalonia.Layout.Layoutable Layoutable()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Layout.Layoutable"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Avalonia.Layout.Layoutable"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Layout.Layoutable"/> class.</returns>
    public static Avalonia.Layout.Layoutable Layoutable(out Avalonia.Layout.Layoutable @ref)
        => @ref = new();
}
