// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="Lucide.Avalonia.LucideIcon"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Lucide.Avalonia.LucideIcon"/> class.</returns>
    public static Lucide.Avalonia.LucideIcon LucideIcon()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="Lucide.Avalonia.LucideIcon"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Lucide.Avalonia.LucideIcon"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="Lucide.Avalonia.LucideIcon"/> class.</returns>
    public static Lucide.Avalonia.LucideIcon LucideIcon(out Lucide.Avalonia.LucideIcon @ref)
        => @ref = new();
}
