// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Locale.pt_PT"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="SukiUI.Locale.pt_PT"/> class.</returns>
    public static SukiUI.Locale.pt_PT pt_PT()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Locale.pt_PT"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="SukiUI.Locale.pt_PT"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="SukiUI.Locale.pt_PT"/> class.</returns>
    public static SukiUI.Locale.pt_PT pt_PT(out SukiUI.Locale.pt_PT @ref)
        => @ref = new();
}
