// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Media.QuadraticBezierSegment"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Avalonia.Media.QuadraticBezierSegment"/> class.</returns>
    public static Avalonia.Media.QuadraticBezierSegment QuadraticBezierSegment()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Media.QuadraticBezierSegment"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Avalonia.Media.QuadraticBezierSegment"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Media.QuadraticBezierSegment"/> class.</returns>
    public static Avalonia.Media.QuadraticBezierSegment QuadraticBezierSegment(out Avalonia.Media.QuadraticBezierSegment @ref)
        => @ref = new();
}
