// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Animation.SizeTransition"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Avalonia.Animation.SizeTransition"/> class.</returns>
    public static Avalonia.Animation.SizeTransition SizeTransition()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Animation.SizeTransition"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Avalonia.Animation.SizeTransition"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Animation.SizeTransition"/> class.</returns>
    public static Avalonia.Animation.SizeTransition SizeTransition(out Avalonia.Animation.SizeTransition @ref)
        => @ref = new();
}
