// <auto-generated />

using Avalonia.Animation;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Styling.Style"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Avalonia.Styling.Style"/> class.</returns>
    public static Avalonia.Styling.Style Style()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Styling.Style"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Avalonia.Styling.Style"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Styling.Style"/> class.</returns>
    public static Avalonia.Styling.Style Style(out Avalonia.Styling.Style @ref)
        => @ref = new();
    
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Styling.Style"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Avalonia.Styling.Style"/> class.</returns>
    public static Style<T> Style<T>() where T : StyledElement => new Style<T>();
    
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Styling.Style"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Avalonia.Styling.Style"/> class.</returns>
    public static Style<T> Style<T>(out Style<T> @ref) where T : StyledElement 
        => @ref = new Style<T>();

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Styling.Style"/> class.
    /// </summary>
    /// <param name="selector">The selector value.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Styling.Style"/> class.</returns>
    public static Avalonia.Styling.Style Style(System.Func<Avalonia.Styling.Selector,Avalonia.Styling.Selector> selector)
        => new(selector);

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Styling.Style"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Avalonia.Styling.Style"/> instantiated class.</param>
    /// <param name="selector">The selector value.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Styling.Style"/> class.</returns>
    public static Avalonia.Styling.Style Style(out Avalonia.Styling.Style @ref, System.Func<Avalonia.Styling.Selector,Avalonia.Styling.Selector> selector)
        => @ref = new(selector);
    
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Styling.Style"/> class.
    /// </summary>
    /// <param name="selector">The selector value.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Styling.Style"/> class.</returns>
    public static Style<T> Style<T>(System.Func<Avalonia.Styling.Selector,Avalonia.Styling.Selector> selector) where T : StyledElement 
        => new Style<T>(selector);

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Styling.Style"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Avalonia.Styling.Style"/> instantiated class.</param>
    /// <param name="selector">The selector value.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Styling.Style"/> class.</returns>
    public static Style<T> Style<T>(out Style<T> @ref, System.Func<Avalonia.Styling.Selector,Avalonia.Styling.Selector> selector) where T : StyledElement 
        => @ref = new Style<T>(selector);
}
