// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment"/> class.</returns>
    public static SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment SukiDesktopEnvironment()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment"/> class.</returns>
    public static SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment SukiDesktopEnvironment(out SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment @ref)
        => @ref = new();
}
