// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.SukiTheme"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="SukiUI.SukiTheme"/> class.</returns>
    public static SukiUI.SukiTheme SukiTheme()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.SukiTheme"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="SukiUI.SukiTheme"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="SukiUI.SukiTheme"/> class.</returns>
    public static SukiUI.SukiTheme SukiTheme(out SukiUI.SukiTheme @ref)
        => @ref = new();
}
