// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Theme.TextEraserButton"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="SukiUI.Theme.TextEraserButton"/> class.</returns>
    public static SukiUI.Theme.TextEraserButton TextEraserButton()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Theme.TextEraserButton"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="SukiUI.Theme.TextEraserButton"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="SukiUI.Theme.TextEraserButton"/> class.</returns>
    public static SukiUI.Theme.TextEraserButton TextEraserButton(out SukiUI.Theme.TextEraserButton @ref)
        => @ref = new();
}
