// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Media.TransformGroup"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="Avalonia.Media.TransformGroup"/> class.</returns>
    public static Avalonia.Media.TransformGroup TransformGroup()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="Avalonia.Media.TransformGroup"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="Avalonia.Media.TransformGroup"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="Avalonia.Media.TransformGroup"/> class.</returns>
    public static Avalonia.Media.TransformGroup TransformGroup(out Avalonia.Media.TransformGroup @ref)
        => @ref = new();
}
