// <auto-generated />

using Avalonia.Animation;
using Avalonia.Styling;

namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia builders.
/// </summary>
public static partial class Builders
{
    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.WindowManager"/> class.
    /// </summary>
    /// <returns>The new instance of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.WindowManager"/> class.</returns>
    public static SukiUI.Controls.Experimental.DesktopEnvironment.WindowManager WindowManager()
        => new();

    /// <summary>
    /// Creates a new instance of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.WindowManager"/> class.
    /// </summary>
    /// <param name="ref">The reference of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.WindowManager"/> instantiated class.</param>
    /// <returns>The new instance of the <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.WindowManager"/> class.</returns>
    public static SukiUI.Controls.Experimental.DesktopEnvironment.WindowManager WindowManager(out SukiUI.Controls.Experimental.DesktopEnvironment.WindowManager @ref)
        => @ref = new();
}
