// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.BusyArea.IsBusyProperty"/> property defined in <see cref="SukiUI.Controls.BusyArea"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> BusyArea_IsBusy => SukiUI.Controls.BusyArea.IsBusyProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.BusyArea.BusyTextProperty"/> property defined in <see cref="SukiUI.Controls.BusyArea"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> BusyArea_BusyText => SukiUI.Controls.BusyArea.BusyTextProperty;
}
