// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.Experimental.ChatUI.MessagesProperty"/> property defined in <see cref="SukiUI.Controls.Experimental.ChatUI"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Collections.ObjectModel.ObservableCollection<SukiUI.Controls.Experimental.ChatMessage>> ChatUI_Messages => SukiUI.Controls.Experimental.ChatUI.MessagesProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.Experimental.ChatUI.TextProperty"/> property defined in <see cref="SukiUI.Controls.Experimental.ChatUI"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> ChatUI_Text => SukiUI.Controls.Experimental.ChatUI.TextProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.Experimental.ChatUI.UserImageSourceProperty"/> property defined in <see cref="SukiUI.Controls.Experimental.ChatUI"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.IImage> ChatUI_UserImageSource => SukiUI.Controls.Experimental.ChatUI.UserImageSourceProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.Experimental.ChatUI.FriendImageSourceProperty"/> property defined in <see cref="SukiUI.Controls.Experimental.ChatUI"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.IImage> ChatUI_FriendImageSource => SukiUI.Controls.Experimental.ChatUI.FriendImageSourceProperty;
}
