// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.CircleProgressBar.ValueProperty"/> property defined in <see cref="SukiUI.Controls.CircleProgressBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> CircleProgressBar_Value => SukiUI.Controls.CircleProgressBar.ValueProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.CircleProgressBar.StrokeWidthProperty"/> property defined in <see cref="SukiUI.Controls.CircleProgressBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> CircleProgressBar_StrokeWidth => SukiUI.Controls.CircleProgressBar.StrokeWidthProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.CircleProgressBar.IsIndeterminateProperty"/> property defined in <see cref="SukiUI.Controls.CircleProgressBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> CircleProgressBar_IsIndeterminate => SukiUI.Controls.CircleProgressBar.IsIndeterminateProperty;
}
