// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.CodeView.TextProperty"/> property defined in <see cref="SukiUI.Controls.CodeView"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.CodeView,System.String> CodeView_Text => SukiUI.Controls.CodeView.TextProperty;
}
