// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.ContentExpandControl.MultiplierProperty"/> property defined in <see cref="SukiUI.Controls.ContentExpandControl"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> ContentExpandControl_Multiplier => SukiUI.Controls.ContentExpandControl.MultiplierProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.ContentExpandControl.OrientationProperty"/> property defined in <see cref="SukiUI.Controls.ContentExpandControl"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Layout.Orientation> ContentExpandControl_Orientation => SukiUI.Controls.ContentExpandControl.OrientationProperty;
}
