// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.GlassCard.CornerRadiusProperty"/> property defined in <see cref="SukiUI.Controls.GlassCard"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.CornerRadius> GlassCard_CornerRadius => SukiUI.Controls.GlassCard.CornerRadiusProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.GlassCard.BorderThicknessProperty"/> property defined in <see cref="SukiUI.Controls.GlassCard"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Thickness> GlassCard_BorderThickness => SukiUI.Controls.GlassCard.BorderThicknessProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.GlassCard.IsAnimatedProperty"/> property defined in <see cref="SukiUI.Controls.GlassCard"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> GlassCard_IsAnimated => SukiUI.Controls.GlassCard.IsAnimatedProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.GlassCard.IsOpaqueProperty"/> property defined in <see cref="SukiUI.Controls.GlassCard"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> GlassCard_IsOpaque => SukiUI.Controls.GlassCard.IsOpaqueProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.GlassCard.IsInteractiveProperty"/> property defined in <see cref="SukiUI.Controls.GlassCard"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> GlassCard_IsInteractive => SukiUI.Controls.GlassCard.IsInteractiveProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.GlassCard.CommandProperty"/> property defined in <see cref="SukiUI.Controls.GlassCard"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Windows.Input.ICommand> GlassCard_Command => SukiUI.Controls.GlassCard.CommandProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.GlassCard.CommandParameterProperty"/> property defined in <see cref="SukiUI.Controls.GlassCard"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> GlassCard_CommandParameter => SukiUI.Controls.GlassCard.CommandParameterProperty;
}
