// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.GroupBox.HeaderProperty"/> property defined in <see cref="SukiUI.Controls.GroupBox"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> GroupBox_Header => SukiUI.Controls.GroupBox.HeaderProperty;
}
