// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Helpers.ConditionalXAML.If.ConditionProperty"/> property defined in <see cref="SukiUI.Helpers.ConditionalXAML.If"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> If_Condition => SukiUI.Helpers.ConditionalXAML.If.ConditionProperty;
}
