// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.SeverityProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.Notifications.NotificationType> InfoBar_Severity => SukiUI.Controls.InfoBar.SeverityProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.IconProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> InfoBar_Icon => SukiUI.Controls.InfoBar.IconProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.IconSizeProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Int32> InfoBar_IconSize => SukiUI.Controls.InfoBar.IconSizeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.IconForegroundProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.IBrush> InfoBar_IconForeground => SukiUI.Controls.InfoBar.IconForegroundProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.IsOpenProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> InfoBar_IsOpen => SukiUI.Controls.InfoBar.IsOpenProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.IsClosableProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> InfoBar_IsClosable => SukiUI.Controls.InfoBar.IsClosableProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.IsOpaqueProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> InfoBar_IsOpaque => SukiUI.Controls.InfoBar.IsOpaqueProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.TitleProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> InfoBar_Title => SukiUI.Controls.InfoBar.TitleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.MessageProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> InfoBar_Message => SukiUI.Controls.InfoBar.MessageProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBar.IsTextSelectableProperty"/> property defined in <see cref="SukiUI.Controls.InfoBar"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> InfoBar_IsTextSelectable => SukiUI.Controls.InfoBar.IsTextSelectableProperty;
}
