// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBadge.AppearanceProperty"/> property defined in <see cref="SukiUI.Controls.InfoBadge"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.Notifications.NotificationType> InfoBadge_Appearance => SukiUI.Controls.InfoBadge.AppearanceProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBadge.CornerPositionProperty"/> property defined in <see cref="SukiUI.Controls.InfoBadge"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Enums.CornerPosition> InfoBadge_CornerPosition => SukiUI.Controls.InfoBadge.CornerPositionProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBadge.IsDotProperty"/> property defined in <see cref="SukiUI.Controls.InfoBadge"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> InfoBadge_IsDot => SukiUI.Controls.InfoBadge.IsDotProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.InfoBadge.OverflowProperty"/> property defined in <see cref="SukiUI.Controls.InfoBadge"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Int32> InfoBadge_Overflow => SukiUI.Controls.InfoBadge.OverflowProperty;
}
