// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.Loading.LoadingStyleProperty"/> property defined in <see cref="SukiUI.Controls.Loading"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Controls.LoadingStyle> Loading_LoadingStyle => SukiUI.Controls.Loading.LoadingStyleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.Loading.ForegroundProperty"/> property defined in <see cref="SukiUI.Controls.Loading"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.IBrush> Loading_Foreground => SukiUI.Controls.Loading.ForegroundProperty;
}
