// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="Lucide.Avalonia.LucideIcon.SizeProperty"/> property defined in <see cref="Lucide.Avalonia.LucideIcon"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> LucideIcon_Size => Lucide.Avalonia.LucideIcon.SizeProperty;

    /// <summary>
    /// The <see cref="Lucide.Avalonia.LucideIcon.ForegroundProperty"/> property defined in <see cref="Lucide.Avalonia.LucideIcon"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.IBrush> LucideIcon_Foreground => Lucide.Avalonia.LucideIcon.ForegroundProperty;

    /// <summary>
    /// The <see cref="Lucide.Avalonia.LucideIcon.StrokeWidthProperty"/> property defined in <see cref="Lucide.Avalonia.LucideIcon"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> LucideIcon_StrokeWidth => Lucide.Avalonia.LucideIcon.StrokeWidthProperty;

    /// <summary>
    /// The <see cref="Lucide.Avalonia.LucideIcon.KindProperty"/> property defined in <see cref="Lucide.Avalonia.LucideIcon"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Nullable<Lucide.Avalonia.LucideIconKind>> LucideIcon_Kind => Lucide.Avalonia.LucideIcon.KindProperty;
}
