// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="Avalonia.Controls.Shapes.Polygon.PointsProperty"/> property defined in <see cref="Avalonia.Controls.Shapes.Polygon"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Collections.Generic.IList<Avalonia.Point>> Polygon_Points => Avalonia.Controls.Shapes.Polygon.PointsProperty;
}
