// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.PropertyGrid.ItemProperty"/> property defined in <see cref="SukiUI.Controls.PropertyGrid"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.ComponentModel.INotifyPropertyChanged> PropertyGrid_Item => SukiUI.Controls.PropertyGrid.ItemProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.PropertyGrid.InstanceProperty"/> property defined in <see cref="SukiUI.Controls.PropertyGrid"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Controls.InstanceViewModel> PropertyGrid_Instance => SukiUI.Controls.PropertyGrid.InstanceProperty;
}
