// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SettingsLayoutItem.HeaderProperty"/> property defined in <see cref="SukiUI.Controls.SettingsLayoutItem"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.SettingsLayoutItem,System.String> SettingsLayoutItem_Header => SukiUI.Controls.SettingsLayoutItem.HeaderProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SettingsLayoutItem.ContentProperty"/> property defined in <see cref="SukiUI.Controls.SettingsLayoutItem"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.SettingsLayoutItem,Avalonia.Controls.Control> SettingsLayoutItem_Content => SukiUI.Controls.SettingsLayoutItem.ContentProperty;
}
