// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SettingsLayout.ItemsProperty"/> property defined in <see cref="SukiUI.Controls.SettingsLayout"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.SettingsLayout,System.Collections.Generic.IEnumerable<SukiUI.Controls.SettingsLayoutItem>> SettingsLayout_Items => SukiUI.Controls.SettingsLayout.ItemsProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SettingsLayout.StackSummaryWidthProperty"/> property defined in <see cref="SukiUI.Controls.SettingsLayout"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SettingsLayout_StackSummaryWidth => SukiUI.Controls.SettingsLayout.StackSummaryWidthProperty;
}
