// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.Stepper.AlternativeStyleProperty"/> property defined in <see cref="SukiUI.Controls.Stepper"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> Stepper_AlternativeStyle => SukiUI.Controls.Stepper.AlternativeStyleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.Stepper.IndexProperty"/> property defined in <see cref="SukiUI.Controls.Stepper"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Int32> Stepper_Index => SukiUI.Controls.Stepper.IndexProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.Stepper.StepsProperty"/> property defined in <see cref="SukiUI.Controls.Stepper"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Collections.IEnumerable> Stepper_Steps => SukiUI.Controls.Stepper.StepsProperty;
}
