// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment.DesktopBackgroundImageSourceProperty"/> property defined in <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.IImage> SukiDesktopEnvironment_DesktopBackgroundImageSource => SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment.DesktopBackgroundImageSourceProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment.HomeImageSourceProperty"/> property defined in <see cref="SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.IImage> SukiDesktopEnvironment_HomeImageSource => SukiUI.Controls.Experimental.DesktopEnvironment.SukiDesktopEnvironment.HomeImageSourceProperty;
}
