// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.SearchTextProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiSideMenu_SearchText => SukiUI.Controls.SukiSideMenu.SearchTextProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.IsSearchEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenu_IsSearchEnabled => SukiUI.Controls.SukiSideMenu.IsSearchEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.IsContentVisibleProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenu_IsContentVisible => SukiUI.Controls.SukiSideMenu.IsContentVisibleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.SidebarToggleEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenu_SidebarToggleEnabled => SukiUI.Controls.SukiSideMenu.SidebarToggleEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.IsToggleButtonVisibleProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenu_IsToggleButtonVisible => SukiUI.Controls.SukiSideMenu.IsToggleButtonVisibleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.IsMenuExpandedProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenu_IsMenuExpanded => SukiUI.Controls.SukiSideMenu.IsMenuExpandedProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.OpenPaneLengthProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Int32> SukiSideMenu_OpenPaneLength => SukiUI.Controls.SukiSideMenu.OpenPaneLengthProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.TogglePaneButtonPositionProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Layout.HorizontalAlignment> SukiSideMenu_TogglePaneButtonPosition => SukiUI.Controls.SukiSideMenu.TogglePaneButtonPositionProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.IsSelectedItemContentMovableProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenu_IsSelectedItemContentMovable => SukiUI.Controls.SukiSideMenu.IsSelectedItemContentMovableProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.HeaderMinHeightProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SukiSideMenu_HeaderMinHeight => SukiUI.Controls.SukiSideMenu.HeaderMinHeightProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.HeaderContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiSideMenu_HeaderContent => SukiUI.Controls.SukiSideMenu.HeaderContentProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.FooterContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiSideMenu_FooterContent => SukiUI.Controls.SukiSideMenu.FooterContentProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.ContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiSideMenu_Content => SukiUI.Controls.SukiSideMenu.ContentProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenu.UseCustomContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenu"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenu_UseCustomContent => SukiUI.Controls.SukiSideMenu.UseCustomContentProperty;
}
