// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiBackground.StyleProperty"/> property defined in <see cref="SukiUI.Controls.SukiBackground"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Enums.SukiBackgroundStyle> SukiBackground_Style => SukiUI.Controls.SukiBackground.StyleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiBackground.ShaderFileProperty"/> property defined in <see cref="SukiUI.Controls.SukiBackground"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiBackground_ShaderFile => SukiUI.Controls.SukiBackground.ShaderFileProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiBackground.ShaderCodeProperty"/> property defined in <see cref="SukiUI.Controls.SukiBackground"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiBackground_ShaderCode => SukiUI.Controls.SukiBackground.ShaderCodeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiBackground.AnimationEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiBackground"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiBackground_AnimationEnabled => SukiUI.Controls.SukiBackground.AnimationEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiBackground.TransitionsEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiBackground"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiBackground_TransitionsEnabled => SukiUI.Controls.SukiBackground.TransitionsEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiBackground.TransitionTimeProperty"/> property defined in <see cref="SukiUI.Controls.SukiBackground"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SukiBackground_TransitionTime => SukiUI.Controls.SukiBackground.TransitionTimeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiBackground.ForceSoftwareRenderingProperty"/> property defined in <see cref="SukiUI.Controls.SukiBackground"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiBackground_ForceSoftwareRendering => SukiUI.Controls.SukiBackground.ForceSoftwareRenderingProperty;
}
