// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialog.ViewModelProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialog"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiDialog_ViewModel => SukiUI.Controls.SukiDialog.ViewModelProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialog.TitleProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialog"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiDialog_Title => SukiUI.Controls.SukiDialog.TitleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialog.ContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialog"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiDialog_Content => SukiUI.Controls.SukiDialog.ContentProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialog.IsViewModelOnlyProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialog"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiDialog_IsViewModelOnly => SukiUI.Controls.SukiDialog.IsViewModelOnlyProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialog.IconProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialog"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiDialog_Icon => SukiUI.Controls.SukiDialog.IconProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialog.ShowCardBackgroundProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialog"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiDialog_ShowCardBackground => SukiUI.Controls.SukiDialog.ShowCardBackgroundProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialog.IconColorProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialog"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.IBrush> SukiDialog_IconColor => SukiUI.Controls.SukiDialog.IconColorProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialog.ActionButtonsProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialog"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Collections.ObjectModel.ObservableCollection<System.Object>> SukiDialog_ActionButtons => SukiUI.Controls.SukiDialog.ActionButtonsProperty;
}
