// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialogHost.ManagerProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialogHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Dialogs.ISukiDialogManager> SukiDialogHost_Manager => SukiUI.Controls.SukiDialogHost.ManagerProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialogHost.DialogProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialogHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiDialogHost_Dialog => SukiUI.Controls.SukiDialogHost.DialogProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiDialogHost.IsDialogOpenProperty"/> property defined in <see cref="SukiUI.Controls.SukiDialogHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiDialogHost_IsDialogOpen => SukiUI.Controls.SukiDialogHost.IsDialogOpenProperty;
}
