// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.UseAlternativeHeaderStyleProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiMessageBoxHost_UseAlternativeHeaderStyle => SukiUI.Controls.SukiMessageBoxHost.UseAlternativeHeaderStyleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.IconProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiMessageBoxHost_Icon => SukiUI.Controls.SukiMessageBoxHost.IconProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.IconPresetProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Nullable<SukiUI.MessageBox.SukiMessageBoxIcons>> SukiMessageBoxHost_IconPreset => SukiUI.Controls.SukiMessageBoxHost.IconPresetProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.IconPresetSizeProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SukiMessageBoxHost_IconPresetSize => SukiUI.Controls.SukiMessageBoxHost.IconPresetSizeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.ShowHeaderContentSeparatorProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiMessageBoxHost_ShowHeaderContentSeparator => SukiUI.Controls.SukiMessageBoxHost.ShowHeaderContentSeparatorProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.FooterLeftItemsSourceProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.Controls> SukiMessageBoxHost_FooterLeftItemsSource => SukiUI.Controls.SukiMessageBoxHost.FooterLeftItemsSourceProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.ActionButtonsSourceProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Collections.AvaloniaList<Avalonia.Controls.Button>> SukiMessageBoxHost_ActionButtonsSource => SukiUI.Controls.SukiMessageBoxHost.ActionButtonsSourceProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.ActionButtonsPresetProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Nullable<SukiUI.MessageBox.SukiMessageBoxButtons>> SukiMessageBoxHost_ActionButtonsPreset => SukiUI.Controls.SukiMessageBoxHost.ActionButtonsPresetProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMessageBoxHost.ItemsSpacingProperty"/> property defined in <see cref="SukiUI.Controls.SukiMessageBoxHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Int32> SukiMessageBoxHost_ItemsSpacing => SukiUI.Controls.SukiMessageBoxHost.ItemsSpacingProperty;
}
