// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMainHost.BackgroundAnimationEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiMainHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiMainHost_BackgroundAnimationEnabled => SukiUI.Controls.SukiMainHost.BackgroundAnimationEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMainHost.BackgroundStyleProperty"/> property defined in <see cref="SukiUI.Controls.SukiMainHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Enums.SukiBackgroundStyle> SukiMainHost_BackgroundStyle => SukiUI.Controls.SukiMainHost.BackgroundStyleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMainHost.BackgroundShaderFileProperty"/> property defined in <see cref="SukiUI.Controls.SukiMainHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiMainHost_BackgroundShaderFile => SukiUI.Controls.SukiMainHost.BackgroundShaderFileProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMainHost.BackgroundShaderCodeProperty"/> property defined in <see cref="SukiUI.Controls.SukiMainHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiMainHost_BackgroundShaderCode => SukiUI.Controls.SukiMainHost.BackgroundShaderCodeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMainHost.BackgroundTransitionsEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiMainHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiMainHost_BackgroundTransitionsEnabled => SukiUI.Controls.SukiMainHost.BackgroundTransitionsEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMainHost.BackgroundTransitionTimeProperty"/> property defined in <see cref="SukiUI.Controls.SukiMainHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SukiMainHost_BackgroundTransitionTime => SukiUI.Controls.SukiMainHost.BackgroundTransitionTimeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMainHost.BackgroundForceSoftwareRenderingProperty"/> property defined in <see cref="SukiUI.Controls.SukiMainHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiMainHost_BackgroundForceSoftwareRendering => SukiUI.Controls.SukiMainHost.BackgroundForceSoftwareRenderingProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiMainHost.HostsProperty"/> property defined in <see cref="SukiUI.Controls.SukiMainHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.Controls> SukiMainHost_Hosts => SukiUI.Controls.SukiMainHost.HostsProperty;
}
