// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToastHost.ManagerProperty"/> property defined in <see cref="SukiUI.Controls.SukiToastHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Toasts.ISukiToastManager> SukiToastHost_Manager => SukiUI.Controls.SukiToastHost.ManagerProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToastHost.MaxToastsProperty"/> property defined in <see cref="SukiUI.Controls.SukiToastHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Byte> SukiToastHost_MaxToasts => SukiUI.Controls.SukiToastHost.MaxToastsProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToastHost.PositionProperty"/> property defined in <see cref="SukiUI.Controls.SukiToastHost"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Enums.ToastLocation> SukiToastHost_Position => SukiUI.Controls.SukiToastHost.PositionProperty;
}
