// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenuItem.IconProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenuItem"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiSideMenuItem_Icon => SukiUI.Controls.SukiSideMenuItem.IconProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenuItem.HeaderProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenuItem"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiSideMenuItem_Header => SukiUI.Controls.SukiSideMenuItem.HeaderProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenuItem.PageContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenuItem"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiSideMenuItem_PageContent => SukiUI.Controls.SukiSideMenuItem.PageContentProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenuItem.SideDisplayTemplateProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenuItem"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.Templates.IDataTemplate> SukiSideMenuItem_SideDisplayTemplate => SukiUI.Controls.SukiSideMenuItem.SideDisplayTemplateProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenuItem.IsContentMovableProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenuItem"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenuItem_IsContentMovable => SukiUI.Controls.SukiSideMenuItem.IsContentMovableProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiSideMenuItem.IsTopMenuExpandedProperty"/> property defined in <see cref="SukiUI.Controls.SukiSideMenuItem"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiSideMenuItem_IsTopMenuExpanded => SukiUI.Controls.SukiSideMenuItem.IsTopMenuExpandedProperty;
}
