// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiTransitioningContentControl.ContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiTransitioningContentControl"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiTransitioningContentControl_Content => SukiUI.Controls.SukiTransitioningContentControl.ContentProperty;
}
