// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.IconProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiToast_Icon => SukiUI.Controls.SukiToast.IconProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.DismissStartTimestampProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.SukiToast,System.Double> SukiToast_DismissStartTimestamp => SukiUI.Controls.SukiToast.DismissStartTimestampProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.TitleProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiToast_Title => SukiUI.Controls.SukiToast.TitleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.LoadingStateProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiToast_LoadingState => SukiUI.Controls.SukiToast.LoadingStateProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.CanDismissByClickingProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiToast_CanDismissByClicking => SukiUI.Controls.SukiToast.CanDismissByClickingProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.CanDismissByTimeProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiToast_CanDismissByTime => SukiUI.Controls.SukiToast.CanDismissByTimeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.DismissTimeoutProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.SukiToast,System.TimeSpan> SukiToast_DismissTimeout => SukiUI.Controls.SukiToast.DismissTimeoutProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.InterruptDismissTimerWhileHoverProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiToast_InterruptDismissTimerWhileHover => SukiUI.Controls.SukiToast.InterruptDismissTimerWhileHoverProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.DismissProgressValueProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.SukiToast,System.Double> SukiToast_DismissProgressValue => SukiUI.Controls.SukiToast.DismissProgressValueProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiToast.ActionButtonsProperty"/> property defined in <see cref="SukiUI.Controls.SukiToast"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.SukiToast,System.Collections.ObjectModel.ObservableCollection<System.Object>> SukiToast_ActionButtons => SukiUI.Controls.SukiToast.ActionButtonsProperty;
}
