// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiStackPage.ContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiStackPage"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Object> SukiStackPage_Content => SukiUI.Controls.SukiStackPage.ContentProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiStackPage.LimitProperty"/> property defined in <see cref="SukiUI.Controls.SukiStackPage"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Int32> SukiStackPage_Limit => SukiUI.Controls.SukiStackPage.LimitProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiStackPage.AlwaysGoBackToFirstPageProperty"/> property defined in <see cref="SukiUI.Controls.SukiStackPage"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiStackPage_AlwaysGoBackToFirstPage => SukiUI.Controls.SukiStackPage.AlwaysGoBackToFirstPageProperty;
}
