// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.SukiTheme.IsRightToLeftProperty"/> property defined in <see cref="SukiUI.SukiTheme"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiTheme_IsRightToLeft => SukiUI.SukiTheme.IsRightToLeftProperty;
}
