// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.MaxWidthScreenRatioProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SukiWindow_MaxWidthScreenRatio => SukiUI.Controls.SukiWindow.MaxWidthScreenRatioProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.MaxHeightScreenRatioProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SukiWindow_MaxHeightScreenRatio => SukiUI.Controls.SukiWindow.MaxHeightScreenRatioProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.IsTitleBarVisibleProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_IsTitleBarVisible => SukiUI.Controls.SukiWindow.IsTitleBarVisibleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.TitleBarAutoHideDelayProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Int32> SukiWindow_TitleBarAutoHideDelay => SukiUI.Controls.SukiWindow.TitleBarAutoHideDelayProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.TitleBarAutoShowDelayProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Int32> SukiWindow_TitleBarAutoShowDelay => SukiUI.Controls.SukiWindow.TitleBarAutoShowDelayProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.TitleBarAnimationEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_TitleBarAnimationEnabled => SukiUI.Controls.SukiWindow.TitleBarAnimationEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.TitleFontSizeProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SukiWindow_TitleFontSize => SukiUI.Controls.SukiWindow.TitleFontSizeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.TitleFontWeightProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Media.FontWeight> SukiWindow_TitleFontWeight => SukiUI.Controls.SukiWindow.TitleFontWeightProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.TitleBarContextMenuProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.ContextMenu> SukiWindow_TitleBarContextMenu => SukiUI.Controls.SukiWindow.TitleBarContextMenuProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.LogoContentProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.Control> SukiWindow_LogoContent => SukiUI.Controls.SukiWindow.LogoContentProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.LogoDoubleTapClosesWindowProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_LogoDoubleTapClosesWindow => SukiUI.Controls.SukiWindow.LogoDoubleTapClosesWindowProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.ShowBottomBorderProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_ShowBottomBorder => SukiUI.Controls.SukiWindow.ShowBottomBorderProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.IsMenuVisibleProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_IsMenuVisible => SukiUI.Controls.SukiWindow.IsMenuVisibleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.MenuItemsProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Collections.AvaloniaList<Avalonia.Controls.MenuItem>> SukiWindow_MenuItems => SukiUI.Controls.SukiWindow.MenuItemsProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.RootCornerRadiusProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.CornerRadius> SukiWindow_RootCornerRadius => SukiUI.Controls.SukiWindow.RootCornerRadiusProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.ShowTitlebarBackgroundProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_ShowTitlebarBackground => SukiUI.Controls.SukiWindow.ShowTitlebarBackgroundProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.CanFullScreenProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_CanFullScreen => SukiUI.Controls.SukiWindow.CanFullScreenProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.CanPinProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_CanPin => SukiUI.Controls.SukiWindow.CanPinProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.CanMoveProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_CanMove => SukiUI.Controls.SukiWindow.CanMoveProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.BackgroundAnimationEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_BackgroundAnimationEnabled => SukiUI.Controls.SukiWindow.BackgroundAnimationEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.BackgroundStyleProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<SukiUI.Enums.SukiBackgroundStyle> SukiWindow_BackgroundStyle => SukiUI.Controls.SukiWindow.BackgroundStyleProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.BackgroundShaderFileProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiWindow_BackgroundShaderFile => SukiUI.Controls.SukiWindow.BackgroundShaderFileProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.BackgroundShaderCodeProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> SukiWindow_BackgroundShaderCode => SukiUI.Controls.SukiWindow.BackgroundShaderCodeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.BackgroundTransitionsEnabledProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_BackgroundTransitionsEnabled => SukiUI.Controls.SukiWindow.BackgroundTransitionsEnabledProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.BackgroundTransitionTimeProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> SukiWindow_BackgroundTransitionTime => SukiUI.Controls.SukiWindow.BackgroundTransitionTimeProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.BackgroundForceSoftwareRenderingProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> SukiWindow_BackgroundForceSoftwareRendering => SukiUI.Controls.SukiWindow.BackgroundForceSoftwareRenderingProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.RightWindowTitleBarControlsProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.Controls> SukiWindow_RightWindowTitleBarControls => SukiUI.Controls.SukiWindow.RightWindowTitleBarControlsProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.HostsProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<Avalonia.Controls.Controls> SukiWindow_Hosts => SukiUI.Controls.SukiWindow.HostsProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.SukiWindow.PreviousVisibleWindowStateProperty"/> property defined in <see cref="SukiUI.Controls.SukiWindow"/> class.
    /// </summary>
    public static Avalonia.DirectProperty<SukiUI.Controls.SukiWindow,Avalonia.Controls.WindowState> SukiWindow_PreviousVisibleWindowState => SukiUI.Controls.SukiWindow.PreviousVisibleWindowStateProperty;
}
