// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Theme.TextEraserButton.TextProperty"/> property defined in <see cref="SukiUI.Theme.TextEraserButton"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.String> TextEraserButton_Text => SukiUI.Theme.TextEraserButton.TextProperty;
}
