// <auto-generated />
namespace Avalonia.Markup.Declarative;

/// <summary>
/// The avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
    /// <summary>
    /// The <see cref="SukiUI.Controls.WaveProgress.ValueProperty"/> property defined in <see cref="SukiUI.Controls.WaveProgress"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Double> WaveProgress_Value => SukiUI.Controls.WaveProgress.ValueProperty;

    /// <summary>
    /// The <see cref="SukiUI.Controls.WaveProgress.IsTextVisibleProperty"/> property defined in <see cref="SukiUI.Controls.WaveProgress"/> class.
    /// </summary>
    public static Avalonia.StyledProperty<System.Boolean> WaveProgress_IsTextVisible => SukiUI.Controls.WaveProgress.IsTextVisibleProperty;
}
