using System.Diagnostics.CodeAnalysis;

// ReSharper disable once CheckNamespace
namespace Generator;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public static partial class Templates
{
    public static string FileHeaderTemplate = """
// <auto-generated />
using Avalonia.Animation;
using Avalonia.Data;
using Avalonia.Interactivity;
using Avalonia.Styling;
using R3;

namespace Avalonia.Markup.Declarative%Namespace%.Extensions;
""";
}
